//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public int ObjectID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string TaskID { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string NotifyToDepartment { get; set; }
        public string NotifyToStaff { get; set; }
        public bool IsDelete { get; set; }
        public string JobID { get; set; }
    }
}
