//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassStudentView
    {
        public string Name { get; set; }
        public string ClassName { get; set; }
        public string Phone1 { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string FeeType { get; set; }
        public decimal PaidFee { get; set; }
        public int ContactID { get; set; }
        public string ClassID { get; set; }
        public int ID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> T2 { get; set; }
        public Nullable<bool> T3 { get; set; }
        public Nullable<bool> T4 { get; set; }
        public Nullable<bool> T5 { get; set; }
        public Nullable<bool> T6 { get; set; }
        public Nullable<bool> T7 { get; set; }
        public Nullable<bool> T8 { get; set; }
        public bool IsDelete { get; set; }
        public string StatusName { get; set; }
    }
}
