//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTimeTable
    {
        public string ID { get; set; }
        public string ClassID { get; set; }
        public System.DateTime Dates { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Note { get; set; }
        public bool IsStudied { get; set; }
        public Nullable<int> ChangedRoomID { get; set; }
        public Nullable<int> ChangedTeacherID { get; set; }
        public bool IsOff { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
        public string ReasonForChangeDate { get; set; }
        public string Lesson { get; set; }
        public string ReasonChangeRoom { get; set; }
    }
}
