//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassStudentDetail
    {
        public int ID { get; set; }
        public string ClassID { get; set; }
        public int CustomerID { get; set; }
        public int ContactID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateBy { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<bool> IsRetain { get; set; }
        public Nullable<System.DateTime> FeeBeginDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<double> Score { get; set; }
        public string Classification { get; set; }
    }
}
