//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassStudentScoreDetail
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string ClassID { get; set; }
        public Nullable<int> ScoreDetailID { get; set; }
        public Nullable<double> Score { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<short> Times { get; set; }
    }
}
