//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactStatusCountByDateAndStaffView
    {
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ToTalCount { get; set; }
        public string AssignTo { get; set; }
    }
}
