//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfoLog
    {
        public int ID { get; set; }
        public int ContactID { get; set; }
        public string Info { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string Type { get; set; }
    }
}
