//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactView
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int StatusID { get; set; }
        public int SubStatusID { get; set; }
        public string Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string ProvinceID { get; set; }
        public string DistrictID { get; set; }
        public string WardID { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public string NoteOld { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public bool IsDelete { get; set; }
        public string Gender { get; set; }
        public bool IsClassRegister { get; set; }
        public string TeacherName { get; set; }
        public string ClassRegisteredID { get; set; }
        public Nullable<bool> IsRegisterForRelative { get; set; }
        public string FBCommentID { get; set; }
        public string SearchText { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> SubSourceID { get; set; }
        public string AssignTo { get; set; }
        public string AssignBy { get; set; }
        public Nullable<System.DateTime> AssignTime { get; set; }
        public Nullable<int> TestSubjectID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.TimeSpan> TestTime { get; set; }
        public Nullable<int> TestTeacherID { get; set; }
        public string TestNote { get; set; }
        public string TestScore { get; set; }
        public Nullable<int> TestResult { get; set; }
        public string DuplicateContactIds { get; set; }
        public string ClassInterestedName { get; set; }
        public string SubjectInterestedName { get; set; }
        public string ContactHomie { get; set; }
        public string TrialClass { get; set; }
        public Nullable<System.DateTime> TrialBeginDate { get; set; }
        public Nullable<System.DateTime> TrialEndDate { get; set; }
        public string TrialNote { get; set; }
        public string StatusName { get; set; }
        public string StatusColor { get; set; }
        public string SubStatusName { get; set; }
        public string SubStatusColor { get; set; }
        public string SourceName { get; set; }
        public string SubSourceName { get; set; }
        public string TestResultName { get; set; }
        public string TestTeacherName { get; set; }
        public string TestSubjectName { get; set; }
    }
}
