//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Customers = new HashSet<Customer>();
            this.Wards = new HashSet<Ward>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string ProvinceID { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Ward> Wards { get; set; }
    }
}
