//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBCommentPr
    {
        public string ID { get; set; }
        public string FBName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Text { get; set; }
        public string ContactID { get; set; }
        public bool IsReply { get; set; }
        public string ParentID { get; set; }
        public string PostID { get; set; }
        public Nullable<bool> UserLike { get; set; }
        public Nullable<bool> IsIngore { get; set; }
        public string Note { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserLink { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsChild { get; set; }
        public string ChildOf { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string TypeOf { get; set; }
        public string Tag { get; set; }
        public string PageID { get; set; }
        public string UrlWeb { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ChildText { get; set; }
        public string ContactIDs { get; set; }
        public string UserChat { get; set; }
        public string PreviewUrl { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ScopedThreadKey { get; set; }
    }
}
