//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GmailAccount
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string Certificate { get; set; }
        public string RefreshToken { get; set; }
        public string AccessToken { get; set; }
    }
}
