//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int ContactID { get; set; }
        public int InvoiceCategoryID { get; set; }
        public int Type { get; set; }
        public string ClassID { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool IsDelete { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string SearchText { get; set; }
        public decimal TotalAmount { get; set; }
        public string DiscountType { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string DiscountReason { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<decimal> PromotionAmount { get; set; }
        public decimal TotalPayment { get; set; }
        public string Payer { get; set; }
        public string Description { get; set; }
        public int AccountID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string ExternalID { get; set; }
        public string Note { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> RetainID { get; set; }
        public Nullable<decimal> RetainAmount { get; set; }
        public Nullable<bool> IsUseRetain { get; set; }
        public Nullable<int> ClassChangingID { get; set; }
        public Nullable<System.DateTime> FeeBeginDate { get; set; }
        public Nullable<System.DateTime> FeeEndDate { get; set; }
    }
}
