//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListSearchCol
    {
        public string ID { get; set; }
        public string Template { get; set; }
        public string Name { get; set; }
        public int ShowIndex { get; set; }
        public bool IsShow { get; set; }
        public int Width { get; set; }
    }
}
