//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public int AppointmentID { get; set; }
        public string Type { get; set; }
        public string Meta { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string NotifyTo { get; set; }
        public System.DateTime NotificationTime { get; set; }
        public bool IsRead { get; set; }
    }
}
