//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Serial { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
