//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreTableStructureDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Coefficient { get; set; }
        public int StructureID { get; set; }
        public int ChildOf { get; set; }
        public Nullable<bool> CheckMany { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Type { get; set; }
    }
}
