//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int ID { get; set; }
        public string ClassID { get; set; }
        public int ContactID { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsAbsent { get; set; }
        public string AbsentNote { get; set; }
    }
}
