//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClassChanging
    {
        public int ID { get; set; }
        public int ContactID { get; set; }
        public string OldClassID { get; set; }
        public decimal OldClassFee { get; set; }
        public int OldClassLesson { get; set; }
        public decimal OldPaid { get; set; }
        public decimal OldRemainAmount { get; set; }
        public int OldStudiedLesson { get; set; }
        public Nullable<decimal> RetainAmount { get; set; }
        public string ChangeReason { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string NewClassID { get; set; }
        public decimal NewClassFee { get; set; }
        public int NewClassLesson { get; set; }
        public decimal NewPaid { get; set; }
        public decimal NewRemainAmount { get; set; }
        public int NewStudiedLesson { get; set; }
        public decimal TotalPay { get; set; }
        public decimal DifferenceAmount { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    }
}
