//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRetainView
    {
        public int ID { get; set; }
        public int ContactID { get; set; }
        public string ClassID { get; set; }
        public decimal ClassFee { get; set; }
        public int ClassLesson { get; set; }
        public decimal Paid { get; set; }
        public decimal RetainAmount { get; set; }
        public int StudiedLesson { get; set; }
        public decimal RemainAmount { get; set; }
        public string RetainReason { get; set; }
        public System.DateTime RetainDate { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string ClassNewID { get; set; }
        public string Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string ContactHomie { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.TimeSpan> ClassBeginTime { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<decimal> RemainFee { get; set; }
    }
}
