//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentView
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string ContactHomie { get; set; }
        public string ClassName { get; set; }
        public string ClassID { get; set; }
        public Nullable<decimal> ClassFee { get; set; }
        public Nullable<int> ClassStatusID { get; set; }
        public Nullable<System.TimeSpan> ClassBeginTime { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }
        public Nullable<bool> T2 { get; set; }
        public Nullable<bool> T3 { get; set; }
        public Nullable<bool> T4 { get; set; }
        public Nullable<bool> T5 { get; set; }
        public Nullable<bool> T6 { get; set; }
        public Nullable<bool> T7 { get; set; }
        public Nullable<bool> T8 { get; set; }
        public Nullable<int> ClassMaxStudent { get; set; }
        public Nullable<int> NumberOfLesson { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string FeeType { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> FeeBeginDate { get; set; }
        public string StatusName { get; set; }
        public int CurrentRegisterCount { get; set; }
        public decimal Paid { get; set; }
        public Nullable<decimal> RemainFee { get; set; }
        public Nullable<System.DateTime> FeeNextDate { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<System.DateTime> FeeEndDate { get; set; }
        public int PaidStatus { get; set; }
    }
}
