//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExtraInfo
    {
        public int ID { get; set; }
        public string ClassID { get; set; }
        public int ContactID { get; set; }
        public bool IsRetain { get; set; }
        public Nullable<System.DateTime> RetainDate { get; set; }
        public Nullable<decimal> RetainAmount { get; set; }
        public string RetainNote { get; set; }
        public bool IsApplyNewClass { get; set; }
        public string NewClassID { get; set; }
    }
}
