//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectCategory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ParentID { get; set; }
        public int OrderIndex { get; set; }
        public string Description { get; set; }
        public string UserCode { get; set; }
        public string SearchText { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
