//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyStatistic
    {
        public int ID { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public string IDClass { get; set; }
        public string Name { get; set; }
        public string NumberPhone { get; set; }
        public int IDSurveyForm { get; set; }
        public string SearchText { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
