//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string UserCode { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Status { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Certificate { get; set; }
        public string University { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public string Images { get; set; }
        public string NumberPassport { get; set; }
        public string PlanceOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpoiration { get; set; }
        public string Visa { get; set; }
        public Nullable<System.DateTime> DateOfExoirationVisa { get; set; }
        public string WorkPermits { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string SearchText { get; set; }
        public bool IsDelete { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<int> CubeID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankAccountNumberOwnerName { get; set; }
        public int BranchID { get; set; }
    }
}
