//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserListSearchInput
    {
        public int ID { get; set; }
        public string InputID { get; set; }
        public bool IsSelected { get; set; }
        public int ShowIndex { get; set; }
        public string UserName { get; set; }
    }
}
