//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserListSearchInputView
    {
        public Nullable<int> ID { get; set; }
        public string InputID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> ShowIndex { get; set; }
    }
}
